import Head from "next/head"
import Read from "@/components/Read"
import Create from "./Create"
import { useRouter } from "next/router";
import Update from './edit/[id]'




export default function Home() {
  const router = useRouter();
  const isCreatePage = router.pathname === "/Create";

  const isEditPage = router.pathname.startsWith(`/edit/`); // Check if the path starts with "/edit/"

  // Extract the ID from the URL
  const id = isEditPage ? router.query.id : null;

  return (
    <>
    <Head>
    <title>Admin Panel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
     <main>
      {!isCreatePage && <Read />}
        {isCreatePage && <Create />}
        {isEditPage && <Update id={id} />}
    </main>
    </>
  )
}
